import {Injectable} from '@angular/core';
@Injectable()
export class PermissionConstant {
    // admin
    static COMPANIES = 'COMPANIES';
    static COMPANIES_CREATE = 'COMPANIES.CREATE';
    static COMPANIES_LIST = 'COMPANIES.LIST';
    static COMPANIES_UPDATE = 'COMPANIES.UPDATE';
    static COMPANIES_DELETE = 'COMPANIES.DELETE';
    static COMPANIES_BANK_CREATE = 'COMAPNIES.BANK.CREATE';
    static TAXES = 'TAXES';
    static TAXES_LIST = 'TAXES.LIST';
    static TAXES_CREATE = 'TAXES.CREATE';
    static TAXES_UPDATE = 'TAXES.EDIT';
    static TAXES_DELETE = 'TAXES.DELETE';

    static COA_LIST = 'COA.LIST';
    static COA_ADD_CHAR_COUNT_CONFIG = 'COA.ADD.CHAR.COUNT.CONFIG';
    static COA_ADMIN_SEGMENT_DETAILS = 'COA.ADMIN.SEGMENT.DETAILS';
    static COA_EDIT = 'COA.EDIT';


    static ROLES_LIST = 'ROLE.LIST';
    static ROLES_ADD = 'ROLE.ADD'; 
    static ROLES_EDIT = 'ROLE.EDIT';
    static ROLES_DELETE = 'ROLE.DELETE';
    static ROLES_PERMISSION_ADD = 'ROLE.PERMISSIONS.ADD';
    static CURRENCIES = 'CURRENCIES';
    static BANKS = 'BANKS';
    static CUSTOMERS = 'PAYERS.PAYEES';
    //static EDIT_COA_ADMIN = 'EDIT.COA.ADMIN'; //ALSO IN HR
    static EDIT_COA_FUNCTIONS = 'EDIT.COA.FUNC';
    static EDIT_COA_PROGRAMME = 'EDIT.COA.PROG';
    static EDIT_COA_GEO = 'EDIT.COA.GEO';
    static EDIT_COA_FUND = 'EDIT.COA.FUND';
    static EDIT_COA_ECONOMIC = 'EDIT.COA.ECONO';
   // static ADD_LOGIN = 'ADD.LOGIN'; //ALSO IN HR
   //static EDIT_LOGIN = 'EDIT.LOGIN' //ALSO IN HR
  //  static DELETE_LOGIN = 'DELETE.LOGIN'; //ALSO IN HR

    // HR
    static EMPLOYEE_LIST = 'EMPLOYEE.LIST';
    static EMPLOYEE_ENROLLMENT_LIST = 'EMPLOYEE.ADD.ENROLLMENT.LIST';
    
    static GRADE_LEVEL_LIST = 'GRADE.LEVEL.LIST';
    static GL_STEP_LIST = 'GL.STEP.LIST';

    static COUNTRIES_ADD = 'COUNTIRES.ADD';
    static COUNTRIES_EDIT = 'COUNTIRES.EDIT';
    static COUNTRIES_LIST = 'COUNTIRES.LIST';
    static COUNTRIES_DELETE = 'COUNTIRES.DELETE';
    static COUNTRIES = 'COUNTIRES';


    static REGION_ADD = 'REGION.ADD';
    static REGION_EDIT = 'REGION.EDIT';
    static REGION_LIST = 'REGION.LIST';
    static REGION_DELETE = 'REGION.DELETE';

    static STATES_ADD = 'STATES.ADD';
    static STATES_EDIT = 'STATES.EDIT';
    static STATES_LIST = 'STATES.LIST';
    static STATES_DELETE = 'STATES.DELETE';

    static LGA_ADD = 'LGA.ADD';
    static LGA_EDIT = 'LGA.EDIT';
    static LGA_LIST = 'LGA.LIST';
    static LGA_DELETE = 'LGA.DELETE';

    static SCHEDULE_ADD = 'SCHEDULE.ADD';
    static SCHEDULE_EDIT = 'SCHEDULE.EDIT';
    static SCHEDULE_LIST = 'SCHEDULE.LIST';
    static SCHEDULE_DELETE = 'SCHEDULE.DELETE';

    static WORK_LOCATION_ADD = 'WORK.LOCATIONS.ADD';
    static WORK_LOCATION_EDIT = 'WORK.LOCATIONS.EDIT';
    static WORK_LOCATION_LIST = 'WORK.LOCATIONS.LIST';
    static WORK_LOCATION_DELETE = 'WORK.LOCATIONS.DELETE';

    static DISENGAGEMENT_ADD = 'DISENGAGEMENT.ADD';
    static DISENGAGEMENT_EDIT = 'DISENGAGEMENT.EDIT';
    static DISENGAGEMENT_LIST = 'DISENGAGEMENT.LIST';
    static DISENGAGEMENT_DELETE = 'DISENGAGEMENT.DELETE';

    static STRUCTURE_ADD = 'STRUCTURE.ADD';
    static STRUCTURE_EDIT = 'STRUCTURE.EDIT';
    static STRUCTURE_LIST = 'STRUCTURE.LIST';
    static STRUCTURE_DELETE = 'STRUCTURE.DELETE';

    static DESIGNATION_ADD = 'DESIGNATIONS.ADD';
    static DESIGNATION_EDIT = 'DESIGNATIONS.EDIT';
    static DESIGNATION_LIST = 'DESIGNATIONS.LIST';
    static DESIGNATION_DELETE = 'DESIGNATIONS.DELETE';

    static SALARYSCALES_ADD = 'SALARY.SCALES.ADD';
    static SALARYSCALES_EDIT = 'SALARY.SCALES.EDIT';
    static SALARYSCALES_LIST = 'SALARY.SCALES.LIST';
    static SALARYSCALES_DELETE = 'SALARY.SCALES.DELETE';

    static QUALIFICATION_ADD = 'QUALIFICATIONS.ADD';
    static QUALIFICATION_EDIT = 'QUALIFICATIONS.EDIT';
    static QUALIFICATION_LIST = 'QUALIFICATIONS.LIST';
    static QUALIFICATION_DELETE = 'QUALIFICATIONS.DELETE';

    static JOB_SKILLS_ADD = 'JOB.SKILLS.ADD';
    static JOB_SKILLS_EDIT = 'JOB.SKILLS.EDIT';
    static JOB_SKILLS_LIST = 'JOB.SKILLS.LIST';
    static JOB_SKILLS_DELETE = 'JOB.SKILLS.DELETE';

    static LANGUAGES_ADD = 'LANGUAGES.ADD';
    static LANGUAGES_EDIT = 'LANGUAGES.EDIT';
    static LANGUAGES_LIST = 'LANGUAGES.LIST';
    static LANGUAGES_DELETE = 'LANGUAGES.DELETE';

    static SCHOOL_CATEGORIES_ADD = 'SCHOOL.CATEGORIES.ADD';
    static SCHOOL_CATEGORIES_EDIT = 'SCHOOL.CATEGORIES.EDIT';
    static SCHOOL_CATEGORIES_LIST = 'SCHOOL.CATEGORIES.LIST';
    static SCHOOL_CATEGORIES_DELETE = 'SCHOOL.CATEGORIES.DELETE';

    static ACADEMIC_MAJORS_ADD = 'ACADEMIC.MAJORS.ADD';
    static ACADEMIC_MAJORS_EDIT = 'ACADEMIC.MAJORS.EDIT';
    static ACADEMIC_MAJORS_LIST = 'ACADEMIC.MAJORS.LIST';
    static ACADEMIC_MAJORS_DELETE = 'ACADEMIC.MAJORS.DELETE';

    static RELATIONS_ADD = 'RELATIONS.ADD';
    static RELATIONS_EDIT = 'RELATIONS.EDIT';
    static RELATIONS_LIST = 'RELATIONS.LIST';
    static RELATIONS_DELETE = 'RELATIONS.DELETE';

    static STAFF_CATEGORIES_ADD = 'STAFF.CATEGORIES.ADD';
    static STAFF_CATEGORIES_EDIT = 'STAFF.CATEGORIES.EDIT';
    static STAFF_CATEGORIES_LIST = 'STAFF.CATEGORIES.LIST';
    static STAFF_CATEGORIES_DELETE = 'STAFF.CATEGORIES.DELETE';

    static STAFF_STATUS_ADD = 'STAFF.STATUS.ADD';
    static STAFF_STATUS_EDIT = 'STAFF.STATUS.EDIT';
    static STAFF_STATUS_LIST = 'STAFF.STATUS.LIST';
    static STAFF_STATUS_DELETE = 'STAFF.STATUS.DELETE';

    static EXIT_OPTIONS_ADD = 'EXIT.OPTIONS.ADD';
    static EXIT_OPTIONS_EDIT = 'EXIT.OPTIONS.EDIT';
    static EXIT_OPTIONS_LIST = 'EXIT.OPTIONS.LIST';
    static EXIT_OPTIONS_DELETE = 'EXIT.OPTIONS.DEKETE';

    static CENSURES_ADD = 'CENSURES.ADD';
    static CENSURES_EDIT = 'CENSURES.EDIT';
    static CENSURES_LIST = 'CENSURES.LIST';
    static CENSURES_DELETE = 'CENSURES.DELETE';

    static ARM_OF_SERVICE_ADD = 'ARMS.OF.SERVICE.ADD';
    static ARM_OF_SERVICE_EDIT = 'ARMS.OF.SERVICE.EDIT';
    static ARM_OF_SERVICE_LIST = 'ARMS.OF.SERVICE.LIST';
    static ARM_OF_SERVICE_DELETE = 'ARMS.OF.SERVICE.DELETE';

    static MEMBERSHIP_ADD = 'MEMBERSHIPS.ADD';
    static MEMBERSHIP_EDIT = 'MEMBERSHIPS.EDIT';
    static MEMBERSHIP_LIST = 'MEMBERSHIPS.LIST';
    static MEMBERSHIP_DELETE = 'MEMBERSHIPS.DELETE';

    static TYPES_OF_LEAVES_ADD = 'TYPES.OF.LEAVE.ADD';
    static TYPES_OF_LEAVES_EDIT = 'TYPES.OF.LEAVE.EDIT';
    static TYPES_OF_LEAVES_LIST = 'TYPES.OF.LEAVE.LIST';
    static TYPES_OF_LEAVES_DELETE = 'TYPES.OF.LEAVE.DELETE';

    static LEAVE_GROUP_ADD = 'LEAVE.GROUP.ADD';
    static LEAVE_GROUP_EDIT = 'LEAVE.GROUP.EDIT';
    static LEAVE_GROUP_LIST = 'LEAVE.GROUP.LIST';
    static LEAVE_GROUP_DELETE = 'LEAVE.GROUP.DELETE';

    static PUBLIC_HOLIDAYS_ADD = 'PUBLIC.HOLIDAYS.ADD';
    static PUBLIC_HOLIDAYS_EDIT = 'PUBLIC.HOLIDAYS.EDIT';
    static PUBLIC_HOLIDAYS_LIST = 'PUBLIC.HOLIDAYS.LIST';
    static PUBLIC_HOLIDAYS_DELETE = 'PUBLIC.HOLIDAYS.DELETE';

    static ADDRESS_ADD = 'ADDRESSES.ADD';
    static ADDRESS_EDIT = 'ADDRESSES.EDIT';
    static ADDRESS_LIST = 'ADDRESSES.LIST';
    static ADDRESS_DELETE = 'ADDRESSES.DELETE';

    static TYPES_OF_PHONE_NUM_ADD = 'TYPES.OF.PHONE.NUM.ADD';
    static TYPES_OF_PHONE_NUM_EDIT = 'TYPES.OF.PHONE.NUM.EDIT';
    static TYPES_OF_PHONE_NUM_LIST = 'TYPES.OF.PHONE.NUM.LIST';
    static TYPES_OF_PHONE_NUM_DELETE = 'TYPES.OF.PHONE.NUM.DELETE';

    static GEO_LOC_ADD = 'GEO.LOC.ADD';
    static GEO_LOC_EDIT = 'GEO.LOC.EDIT';
    static GEO_LOC_LIST = 'GEO.LOC.LIST';
    static GEO_LOC_DELETE = 'GEO.LOC.DELETE';

    static COMPANY_INFO_ADD = 'COMPANY.INFO.ADD';
    static COMPANY_INFO_EDIT = 'COMPANY.INFO.EDIT';
    static COMPANY_INFO_LIST = 'COMPANY.INFO.LIST';
    static COMPANY_INFO_DELETE = 'COMPANY.INFO.DELETE';

    static OFFICE_LOCATION_ADD = 'OFFICE.LOCACTION.ADD';
    static OFFICE_LOCATION_EDIT = 'OFFICE.LOCACTION.EDIT';
    static OFFICE_LOCATION_LIST = 'OFFICE.LOCACTION.LIST';
    static OFFICE_LOCATION_DELETE = 'OFFICE.LOCACTION.DELETE';

    static JOB_POSITION_ADD = 'JOB.POSITION.ADD';
    static JOB_POSITION_EDIT = 'JOB.POSITION.EDIT';
    static JOB_POSITION_LIST = 'JOB.POSITION.LIST';
    static JOB_POSITION_DELETE = 'JOB.POSITION.DELETE';

    static DEPARTMENT_ADD = 'DEPARTMENT.ADD';
    static DEPARTMENT_EDIT = 'DEPARTMENT.EDIT';
    static DEPARTMENT_LIST = 'DEPARTMENT.LIST';
    static DEPARTMENT_DELETE = 'DEPARTMENT.DELETE';

    static ADD_EMPLOYEE = 'ADD.EMPLOYEE';
    static ACTIVATE_EMPLOYEE = 'ACTIVATE.EMPLOYEE';
    static DELETE_EMPLOYEE = 'DELETE.EMPLOYEE';
    static UPDATE_EMPLOYEE_PHOTO_FILE = 'UPDATE.EMPLOYEE.PHOTO.FILE';
    static EDIT_EMPLOYEE = 'EDIT.EMPLOYEE';
    static EDIT_EMLOYEE_DETAIL = 'EDIT.EMPLOYEE.DETAILS';
    static EDIT_EMPLOYEE_ADDRESS = 'EDIT.EMPLOYEE.ADDRESS';
    static EDIT_EMPLOYEE_CENSURE = 'EDIT.EMPLOYEE.CENSURE';
    static EDIT_EMPLOYEE_HISTORY = 'EDIT.EMPLOYEE.HISTORY';
    static EDIT_EMPLOYEE_LANGUAGE = 'EDIT.EMPLOYEE.LANGS';
    static EDIT_EMPLOYEE_PROF_MEMBER = 'EDIT.EMPLOYEE.PROF.MEMBER';
    static EDIT_EMPLOYEE_OTHER_MEMBER = 'EDIT.EMPLOYEE.OTHER.MEMBER';
    static EDIT_EMPLOYEE_MILITARY_SERVICE = 'EDIT.EMPLOYEE.MILITARY.SERVICE';
    static EDIT_EMPLOYEE_PHONE = 'EDIT.EMPLOYEE.PHONES';
    static EDIT_EMPLOYEE_PROGRESS = 'EDIT.EMPLOYEE.PROGRESS';
    static EDIT_EMPLOYEE_QUALIFICATION = 'EDIT.EMPLOYEE.QUALIFICATION';
    static EDIT_EMPLOYEE_RELATIONS = 'EDIT.EMPLOYEE.RELATIONS';
    static EDIT_EMPLOYEE_SCHOOLS = 'EDIT.EMPLOYEE.SCHOOLS';
    static EDIT_EMPLOYEE_SKILLS = 'EDIT.EMPLOYEE.SKILLS';
    static EDIT_EMPLOYEE_PHOTO = 'EDIT.EMPLOYEE.PHOTO';
    static EDIT_EMPLOYEE_EXIT = 'EDIT.EMPLOYEE.EXIT';
    static EDIT_EMPLOYEE_CONFIRM = 'EDIT.EMPLOYEE.CONFIRM';
    static PRINT_EMPLOYEES = 'PRINT.EMPLOYEES';
    static ADD_LOGIN = 'ADD.LOGIN';
    static EDIT_LOGIN = 'EDIT.LOGIN';
    static DELETE_LOGIN = 'DELETE.LOGIN';
    static EDIT_COA_ADMIN_HR = 'EDIT.COA.ADMIN';
    static EDIT_EMPLOYEE_BANK = 'EDIT.EMPLOYEE.BANK';
    static DELETE_EMPLOYEE_4RM_PAYROOL = 'DELETE.EMPLOYEE.4RM.PAYROLL';
    static ADD_EMPLOYEE_TO_PAYROLL = 'ADD.EMPLOYEE.TO.PAYROLL';


    //finance

    static ADD_GL_JV = 'GL.JV.ADD';
    static EDIT_GL_JV = 'GL.JV.EDIT';
    static LIST_GL_JV = 'GL.JV.LIST';
    static DELETE_GL_JV = 'GL.JV.DELETE';
    static CHECK_GL_JV = 'GL.JV.CHECK';
    static POST_GL_JV = 'GL.JV.POST';
    static ADD_ECONOMIC_BUDGET = 'ADD.ECONOMIC.BUDGET';
    static EDIT_ECONOMIC_BUDGET = 'EDIT.ECONOMIC.BUDGET';
    static ECONOMIC_BUDGET_CONTROL_LIST = 'ECONOMIC.BUDGET.CONTROL.LIST';
    static PROGRAMME_BUDGET_CONTROL_LIST = 'PROGRAMME.BUDGET.CONTROL.LIST';
    static COMMIT_PAYMENT_APPROVAL = 'COMMIT.PAYMENT.APPROVAL';
    static POST_TO_GL = 'POST.TP.GL';
    static DELETE_ECONOMIC_BUDGET = 'DELETE.ECONOMIC.BUDGET';
    static ADD_PROGRAMME_BUDGET = 'ADD.PROGRAMME.BUDGET';
    static EDIT_PROGRAMME_BUDGET = 'EDIT.PROGRAMME.BUDGET';
    static DELETE_PROGRAMME_BUDGET = 'DELETE.PROGRAMME.BUDGET';


    //inventory

    static AUTO_UPDATE_FUNCTION_LIST = 'AUTO.UPDATE.FUNCS';
    static DELETE_BUTTON_MAINTENANCE_FORM = 'MAINTCE.DEL';
    static EDIT_BUTTON_MAINTENANCE_FORM = 'MAINTENANCE.EDIT';
    static DELETE_BUTTON_TRANSACTION_FORM = 'TRANSACTION.DEL';
    static EDIT_BUTTON_TRANSACTION_FORM = 'TRANSSACTION.EDIT';
    static USERS_ACCOUNTS = 'USERS';
    static USERS_GROUPS = 'USERS.GROUPS';
    static EDIT_INVENTORY_CATEGORIES = 'EDIT.INVENTORY.CATEGORIES'
    

    static STORE_SETUP_ITEMS_ADD = 'ITEMS.ADD';
    static STORE_SETUP_ITEMS_EDIT = 'ITEMS.EDIT';
    static STORE_SETUP_ITEMS_LIST = 'ITEMS.LIST';
    static STORE_SETUP_ITEMS_DELETE = 'ITEMS.DELETE';

    static STORE_SETUP_CATEGORIES_ADD = 'CATEGORIES.ADD';
    static STORE_SETUP_CATEGORIES_EDIT = 'CATEGORIES.EDIT';
    static STORE_SETUP_CATEGORIES_LIST = 'CATEGORIES.LIST';
    static STORE_SETUP_CATEGORIES_DELETE = 'CATEGORIES.DELETE';

    static STORE_SETUP_STORES_ADD = 'STORES.ADD';
    static STORE_SETUP_STORES_EDIT = 'STORES.EDIT';
    static STORE_SETUP_STORES_LIST = 'STORES.LIST';
    static STORE_SETUP_STORES_DELETE = 'STORES.DELETE';

    static STORE_SETUP_UNIT_OF_MEASURES_ADD = 'UNIT.OF.MEASURES.ADD';
    static STORE_SETUP_UNIT_OF_MEASURES_EDIT = 'UNIT.OF.MEASURES.EDIT';
    static STORE_SETUP_UNIT_OF_MEASURES_LIST = 'UNIT.OF.MEASURES.LIST';
    static STORE_SETUP_UNIT_OF_MEASURES_DELETE = 'UNIT.OF.MEASURES.DELETE';

    static SRV_PURCHASE_INVOICE_LIST = 'SRV.PURCHASE.INVOICE.LIST';
    static SRV_PURCHASE_RETURN_LIST = 'SRV.PURCHASE.RETURN.LIST';
    static SALES_INVOICE_LIST = 'SALES.INVOICE.LIST';
    static SALES_RETURN_BY_CUSTOMER_LIST = 'SALES.RETURN.BY.CUSTOMER.LIST';
    static STV_STORE_TRANSFER_LIST = 'STV.STORE.TRANSFER.LIST';
    static STORE_ADJUSTMENT_LIST = 'STORE.ADJUSTMENT.LIST';
    static DONATION_LIST = 'TRANSACTION.DONATION.LIST';

    static BIN_CARD_LIST = 'BIN.CARD.LIST';
    static INVENTORY_LEDGER_LIST = 'INVENTORY.LEDGER.LIST';
    static QUALITY_BALANCE_LIST = 'QUALITY.BALANCE.LIST';
    static OFF_LEVEL_LIST = 'OFF.LEVEL.LIST';
}
